// This file is the entry script for Webpack's ts-loader. Do not edit this file.
import Game from '../../core/models/game';
import { custom_commands } from './commands';
import { event_handlers } from './event-handlers';

export let game = new Game();
game.registerAdventureLogic(event_handlers, custom_commands);
