# Generated by Django 2.0.2 on 2018-04-15 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventure', '0048_auto_20180304_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('data', models.TextField(max_length=1000000, null=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_games', to='adventure.Adventure')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_games', to='adventure.Player')),
            ],
        ),
    ]
