# Generated by Django 2.2.1 on 2019-07-04 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0058_auto_20190703_2149'),
        ('player', '0002_savedgame_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, null=True)),
                ('overall', models.IntegerField(blank=True, null=True)),
                ('combat', models.IntegerField(blank=True, null=True)),
                ('puzzle', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='adventure.Adventure')),
            ],
        ),
    ]
