# Generated by Django 3.2.12 on 2022-05-15 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=6)),
                ('hardiness', models.IntegerField(default=12)),
                ('agility', models.IntegerField(default=12)),
                ('charisma', models.IntegerField(default=12)),
                ('gold', models.IntegerField(default=200)),
                ('gold_in_bank', models.IntegerField(default=0)),
                ('wpn_axe', models.IntegerField(default=5, verbose_name='Axe ability')),
                ('wpn_bow', models.IntegerField(default=-10, verbose_name='Bow/missile ability')),
                ('wpn_club', models.IntegerField(default=20, verbose_name='Club ability')),
                ('wpn_spear', models.IntegerField(default=10, verbose_name='Spear/Polearm ability')),
                ('wpn_sword', models.IntegerField(default=0, verbose_name='Sword ability')),
                ('armor_expertise', models.IntegerField(default=0)),
                ('spl_blast', models.IntegerField(default=0, verbose_name='Blast ability')),
                ('spl_heal', models.IntegerField(default=0, verbose_name='Heal ability')),
                ('spl_power', models.IntegerField(default=0, verbose_name='Power ability')),
                ('spl_speed', models.IntegerField(default=0, verbose_name='Speed ability')),
                ('uuid', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.CharField(max_length=100, null=True)),
                ('uuid', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerArtifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('type', models.IntegerField(choices=[(2, 'Weapon'), (3, 'Magic Weapon'), (11, 'Wearable')])),
                ('weight', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('weapon_type', models.IntegerField(choices=[(1, 'Axe'), (2, 'Bow'), (3, 'Club'), (4, 'Spear'), (5, 'Sword')], default=0, null=True)),
                ('hands', models.IntegerField(choices=[(1, 'One-handed'), (2, 'Two-handed')], default=1)),
                ('weapon_odds', models.IntegerField(default=0, null=True)),
                ('dice', models.IntegerField(default=1, null=True)),
                ('sides', models.IntegerField(default=1, null=True)),
                ('armor_type', models.IntegerField(choices=[(0, 'Armor'), (1, 'Shield'), (2, 'Helmet'), (3, 'Gloves'), (4, 'Ring')], default=0, null=True)),
                ('armor_class', models.IntegerField(default=0, null=True)),
                ('armor_penalty', models.IntegerField(default=0, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='player.player')),
            ],
        ),
    ]
