# Generated by Django 3.2.12 on 2022-05-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_player_playerartifact_playerprofile'),
    ]

    operations = [
        migrations.RunSQL('SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0'),

        migrations.RunSQL(
            'REPLACE INTO eamon.player_player '
            '(id, name, gender, hardiness, agility, charisma, gold, '
            'gold_in_bank, wpn_axe, wpn_bow, wpn_club, wpn_spear, wpn_sword, '
            'armor_expertise, spl_blast, spl_heal, spl_power, spl_speed, uuid) '
            ' SELECT id, name, gender, hardiness, agility, charisma, gold, '
            'gold_in_bank, wpn_axe, wpn_bow, wpn_club, wpn_spear, wpn_sword, '
            'armor_expertise, spl_blast, spl_heal, spl_power, spl_speed, uuid '
            ' FROM adventure_player'),

        migrations.RunSQL(
            'REPLACE INTO eamon.player_playerartifact '
            '(name, description, `type`, weight, value, weapon_type, hands, weapon_odds, '
            'dice, sides, armor_type, armor_class, armor_penalty, player_id) '
            ' SELECT name, description, `type`, weight, value, weapon_type, hands, weapon_odds, '
            'dice, sides, armor_type, armor_class, armor_penalty, player_id '
            ' FROM adventure_playerartifact'),

        migrations.RunSQL(
            'REPLACE INTO eamon.player_playerprofile (social_id, uuid) '
            'SELECT social_id, uuid FROM adventure_playerprofile'),

        migrations.RunSQL('SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS')
    ]
