# Generated by Django 3.2.6 on 2022-05-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0067_roomexit_hintanswer_adventure_id'),
        ('player', '0007_playerprofile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('adventure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_activity_log', to='adventure.adventure')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='player.player')),
            ],
        ),
    ]
