// This file is the entry script for Webpack's ts-loader. Do not edit this file.
import { Game } from '../../core/models/game';
import { custom_commands } from './commands'
import { event_handlers } from './event-handlers'

export let game = new Game();
game.registerEventHandlers(event_handlers);
game.custom_commands = custom_commands;
