# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('edx', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('room_id', models.IntegerField(help_text='If in a room, the room ID', null=True)),
                ('monster_id', models.IntegerField(help_text='If carried by a monster, the monster ID', null=True)),
                ('container_id', models.IntegerField(help_text='If in a container, the container ID', null=True)),
                ('weight', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(0, 'Gold'), (1, 'Treasure'), (2, 'Weapon'), (3, 'Magic Weapon'), (4, 'Container'), (5, 'Light Source'), (6, 'Drinkable'), (7, 'Readable'), (8, 'Door/Gate'), (9, 'Edible'), (10, 'Bound Monster'), (11, 'Wearable'), (12, 'Disguised Monster'), (13, 'Dead Body'), (14, 'User 1'), (15, 'User 2'), (16, 'User 3')], null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('weapon_type', models.IntegerField(choices=[(1, 'Axe'), (2, 'Bow'), (3, 'Club'), (4, 'Spear'), (5, 'Sword')], null=True)),
                ('hands', models.IntegerField(choices=[(1, 'One-handed'), (2, 'Two-handed')], default=1)),
                ('weapon_odds', models.IntegerField(null=True)),
                ('dice', models.IntegerField(null=True)),
                ('sides', models.IntegerField(null=True)),
                ('armor_class', models.IntegerField(default=0)),
                ('get_all', models.BooleanField(default=True, help_text="Will the 'get all' command pick up this item?")),
                ('embedded', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(help_text='Drinks or bites, fuel for light source, etc.', null=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='adventure.Adventure')),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactMarking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marking', models.TextField(max_length=65535)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.Artifact')),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('hardiness', models.IntegerField(default=12)),
                ('agility', models.IntegerField(default=12)),
                ('friendliness', models.CharField(choices=[('friend', 'Always Friendly'), ('neutral', 'Always Neutral'), ('hostile', 'Always Hostile'), ('random', 'Random')], max_length=10)),
                ('friend_odds', models.IntegerField(default=50)),
                ('combat_code', models.IntegerField(choices=[(1, 'Attacks using generic ATTACK message (e.g., slime, snake, bird)'), (0, 'Uses weapon, or with natural weapons if specified (default)'), (-1, 'Use weapon if it has one, otherwise natural weapons'), (-2, 'Never fights')], default=0)),
                ('courage', models.IntegerField(default=100)),
                ('room_id', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('none', 'None')], max_length=6)),
                ('weapon_id', models.IntegerField(null=True)),
                ('attack_odds', models.IntegerField(default=50)),
                ('weapon_dice', models.IntegerField(default=1)),
                ('weapon_sides', models.IntegerField(default=4)),
                ('defense_bonus', models.IntegerField(default=0, help_text='Special defensive bonus making monster harder to hit')),
                ('armor_class', models.IntegerField(default=0)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='adventure.Adventure')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('hardiness', models.IntegerField(default=12)),
                ('agility', models.IntegerField(default=12)),
                ('charisma', models.IntegerField(default=12)),
                ('gold', models.IntegerField(default=200)),
                ('gold_in_bank', models.IntegerField(default=0)),
                ('wpn_axe', models.IntegerField(default=5, verbose_name='Axe ability')),
                ('wpn_bow', models.IntegerField(default=-10, verbose_name='Bow/missile ability')),
                ('wpn_club', models.IntegerField(default=20, verbose_name='Club ability')),
                ('wpn_spear', models.IntegerField(default=10, verbose_name='Spear/Polearm ability')),
                ('wpn_sword', models.IntegerField(default=0, verbose_name='Sword ability')),
                ('armor_expertise', models.IntegerField(default=0)),
                ('spl_blast', models.IntegerField(default=0, verbose_name='Blast ability')),
                ('spl_heal', models.IntegerField(default=0, verbose_name='Heal ability')),
                ('spl_power', models.IntegerField(default=0, verbose_name='Power ability')),
                ('spl_speed', models.IntegerField(default=0, verbose_name='Speed ability')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerArtifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('type', models.IntegerField(choices=[(2, 'Weapon'), (3, 'Magic Weapon'), (11, 'Wearable')])),
                ('weapon_type', models.IntegerField(choices=[(1, 'Axe'), (2, 'Bow'), (3, 'Club'), (4, 'Spear'), (5, 'Sword')], default=0)),
                ('odds', models.IntegerField(default=0)),
                ('dice', models.IntegerField(default=1)),
                ('sides', models.IntegerField(default=1)),
                ('armor_type', models.IntegerField(choices=[(0, 'Armor'), (1, 'Shield')], default=0)),
                ('armor_class', models.IntegerField(default=0)),
                ('armor_penalty', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='adventure.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('is_dark', models.BooleanField(default=0)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='adventure.Adventure')),
            ],
        ),
        migrations.CreateModel(
            name='RoomExit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=2)),
                ('room_to', models.IntegerField(default=0)),
                ('key_id', models.IntegerField(null=True)),
                ('message', models.CharField(max_length=255)),
                ('room_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exits', to='adventure.Room')),
            ],
        ),
    ]
