# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='is_worn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monster',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monster',
            name='original_group_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='monster',
            name='room_id',
            field=models.IntegerField(null=True),
        ),
    ]
