# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20160220_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_id', models.IntegerField(default=0)),
                ('text', models.TextField(max_length=65535)),
            ],
        ),
        migrations.AddField(
            model_name='adventure',
            name='edx_artifact_offset',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='edx_effect_offset',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='edx_monster_offset',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='edx_room_offset',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='adventure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='adventure.Adventure'),
        ),
    ]
