# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20160223_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='edx',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
