# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20160223_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='directions',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='adventure',
            name='edx_version',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
