# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_effect_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='effect',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='effect_inline',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='next',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='next_inline',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='effect',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='effect_inline',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='effect',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='effect_inline',
            field=models.IntegerField(null=True),
        ),
    ]
