# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0009_adventure_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='guard_id',
            field=models.IntegerField(help_text='If a bound monster, the ID of a monster that prevents the player from freeing it', null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='key_id',
            field=models.IntegerField(help_text='If a container, door, or bound monster, the artifact ID of the key that opens it', null=True),
        ),
    ]
