# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0010_auto_20160327_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='effect_id',
            field=models.IntegerField(help_text='First effect ID for Readable artifacts', null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='num_effects',
            field=models.IntegerField(help_text='Number of effects for Readable artifacts (legacy)', null=True),
        ),
    ]
