# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0012_adventure_edx_program_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='synonyms',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='synonyms',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
