# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0015_auto_20160503_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerartifact',
            old_name='odds',
            new_name='weapon_odds',
        ),
    ]
