# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0016_auto_20160504_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='active',
            field=models.BooleanField(default=0),
        ),
    ]
