# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0017_adventure_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='armor_type',
            field=models.IntegerField(choices=[(0, 'Armor'), (1, 'Shield')], null=True),
        ),
    ]
