# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0018_artifact_armor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='clothing_type',
            field=models.IntegerField(choices=[(0, 'Clothes or Armor/Shield'), (1, 'Coats, Capes, etc.'), (2, 'Shoes, boots'), (3, 'Gloves'), (4, 'Hats, headwear'), (5, 'Jewelry'), (6, 'Undergarments')], null=True),
        ),
    ]
