# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0019_artifact_clothing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerartifact',
            name='armor_class',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerartifact',
            name='armor_penalty',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerartifact',
            name='armor_type',
            field=models.IntegerField(choices=[(0, 'Armor'), (1, 'Shield')], default=0, null=True),
        ),
    ]
