# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0020_auto_20160530_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
