# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0021_artifact_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='hardiness',
            field=models.IntegerField(help_text='If a door or container that must be smashed open, how much damage does it take to open it?', null=True),
        ),
    ]
