# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0023_auto_20160601_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('edx', models.CharField(max_length=50, null=True)),
                ('question', models.CharField(max_length=255)),
                ('adventure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='adventure.Adventure')),
            ],
        ),
        migrations.CreateModel(
            name='HintAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('answer', models.TextField(max_length=1000)),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='adventure.Hint')),
            ],
        ),
    ]
