# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0025_auto_20161029_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='uuid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
