# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('adventure', '0026_player_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='intro_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
