# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0028_auto_20170114_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='intro_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
