# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0029_auto_20170114_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='full_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
