# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0031_auto_20170119_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='armor_penalty',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
