# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0033_playerartifact_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='dead_body_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
