# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0035_auto_20170206_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('adventure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='adventure.Adventure')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='adventure.Player')),
            ],
        ),
    ]
