# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0037_auto_20170330_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='first_hint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='last_hint',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
