# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0038_auto_20170330_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='next',
            field=models.IntegerField(help_text='The next chained effect. Used with EDX conversions.', null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='next_inline',
            field=models.IntegerField(help_text='The next chained effect, no line break. Used with EDX conversions.', null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='style',
            field=models.CharField(choices=[('', 'Normal'), ('success', 'Success (green)'), ('special', 'Special 1 (blue)'), ('special2', 'Special 1 (purple)'), ('warning', 'Warning (orange)'), ('danger', 'Danger (red)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='effect',
            field=models.IntegerField(help_text='Used only with EDX conversions', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='effect_inline',
            field=models.IntegerField(help_text='Used only with EDX conversions', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='friend_odds',
            field=models.IntegerField(default=50, help_text="Used when 'Friendliness' is 'Random'"),
        ),
        migrations.AlterField(
            model_name='monster',
            name='synonyms',
            field=models.CharField(help_text="Other names used for this monster. If the name is 'python' a synonym might be 'snake'", max_length=255, null=True),
        ),
    ]
