# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0040_auto_20170423_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='edx',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='edx_artifact_offset',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='edx_effect_offset',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='edx_monster_offset',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='edx_program_file',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='edx_room_offset',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='armor_penalty',
            field=models.IntegerField(default=0, help_text="(Armor only) How much does this reduce the player's chance to hit, if they don't have enougharmor expertise?", null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='armor_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Armor'), (1, 'Shield')], null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='clothing_type',
            field=models.IntegerField(choices=[(0, 'Clothes or Armor/Shield'), (1, 'Coats, Capes, etc.'), (2, 'Shoes, boots'), (3, 'Gloves'), (4, 'Hats, headwear'), (5, 'Jewelry'), (6, 'Undergarments')], help_text='Reserved for future use.', null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='container_id',
            field=models.IntegerField(blank=True, help_text='If in a container, the container ID', null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='dice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='effect',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='effect_id',
            field=models.IntegerField(blank=True, help_text='First effect ID for Readable artifacts', null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='effect_inline',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='embedded',
            field=models.BooleanField(default=False, help_text='Check this box to make the item not appear in the artifacts list until the player looks at it.'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='guard_id',
            field=models.IntegerField(blank=True, help_text='If a bound monster, the ID of a monster that prevents the player from freeing it', null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='hardiness',
            field=models.IntegerField(blank=True, help_text='If a door or container that must be smashed open, how much damage does it take to open it?', null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='hidden',
            field=models.BooleanField(default=False, help_text="(For secret doors only) Check this box for embedded secret doors, so that the player can'tpass through them before finding them."),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='key_id',
            field=models.IntegerField(blank=True, help_text='If a container, door, or bound monster, the artifact ID of the key that opens it', null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='monster_id',
            field=models.IntegerField(blank=True, help_text='If carried by a monster, the monster ID', null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='num_effects',
            field=models.IntegerField(blank=True, help_text='Number of effects for Readable artifacts', null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Drinks or bites, fuel for light source, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='room_id',
            field=models.IntegerField(blank=True, help_text='If in a room, the room ID', null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='sides',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='synonyms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='weapon_odds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='weapon_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Axe'), (2, 'Bow'), (3, 'Club'), (4, 'Spear'), (5, 'Sword')], null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='weight',
            field=models.IntegerField(default=0, help_text="Weight in Gronds. Enter -999 for something that can't be picked up, or 999 to show the message'Don't be absurd' if the player tries to pick it up."),
        ),
        migrations.AlterField(
            model_name='monster',
            name='attack_odds',
            field=models.IntegerField(default=50, help_text='Base attack odds, before agility and armor adjustments. Weapon type does not matter.'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='defense_bonus',
            field=models.IntegerField(default=0, help_text='no longer used'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='friend_odds',
            field=models.IntegerField(default=50, help_text="Used only when 'Friendliness' is 'Random'"),
        ),
        migrations.AlterField(
            model_name='monster',
            name='original_group_size',
            field=models.IntegerField(default=1, help_text='no longer used'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='synonyms',
            field=models.CharField(blank=True, help_text="Other names used for this monster. If the name is 'python' a synonym might be 'snake'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='weapon_dice',
            field=models.IntegerField(default=1, help_text="Applies to natural weapons only. For an artifact weapon, the weapon's dice and sides will be used."),
        ),
        migrations.AlterField(
            model_name='monster',
            name='weapon_id',
            field=models.IntegerField(help_text='Enter an artifact ID, or zero for natural weapons. Leave blank for no weapon.', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='weapon_sides',
            field=models.IntegerField(default=4, help_text='Applies to natural weapons only.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='effect',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='effect_inline',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomexit',
            name='door_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomexit',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
