# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0041_auto_20170530_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
