# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0042_activitylog_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='pursues',
            field=models.BooleanField(default=True, help_text='Will the monster pursue a fleeing player?'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='synonyms',
            field=models.CharField(blank=True, help_text="Other terms for this artifact. E.g., if the artifact name is 'secret door in north wall' you could have a synonym of 'door' to help the player find it.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='next',
            field=models.IntegerField(blank=True, help_text='The next chained effect. Used with EDX conversions.', null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='next_inline',
            field=models.IntegerField(blank=True, help_text='The next chained effect, no line break. Used with EDX conversions.', null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='style',
            field=models.CharField(blank=True, choices=[('', 'Normal'), ('success', 'Success (green)'), ('special', 'Special 1 (blue)'), ('special2', 'Special 1 (purple)'), ('warning', 'Warning (orange)'), ('danger', 'Danger (red)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='room_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='weapon_id',
            field=models.IntegerField(blank=True, help_text='Enter an artifact ID, or zero for natural weapons. Leave blank for no weapon.', null=True),
        ),
    ]
