# Generated by Django 2.0 on 2018-01-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0044_auto_20180124_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='armor_penalty',
            field=models.IntegerField(default=0, help_text="(Armor only) How much does this reduce the player's chance to hit, if they don't have enough armor expertise?", null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='hardiness',
            field=models.IntegerField(blank=True, help_text='If a door or container that can be smashed open, how much damage does it take to open it?', null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='hidden',
            field=models.BooleanField(default=False, help_text="(For secret doors only) Check this box for embedded secret doors, so that the player can't pass through them before finding them."),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='weight',
            field=models.IntegerField(default=0, help_text="Weight in Gronds. Enter -999 for something that can't be picked up, or 999 to show the message 'Don't be absurd' if the player tries to pick it up."),
        ),
        migrations.AlterField(
            model_name='monster',
            name='container_id',
            field=models.IntegerField(blank=True, help_text='Container artifact ID where this monster starts. The monster will enter the room as soon as the container is opened. e.g., a vampire who awakes when you open his coffin', null=True),
        ),
    ]
