# Generated by Django 2.0 on 2018-01-28 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0045_auto_20180127_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='adventure.Player'),
        ),
    ]
