# Generated by Django 2.0.2 on 2018-02-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0046_auto_20180128_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.CharField(max_length=100, null=True)),
                ('uuid', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
