# Generated by Django 2.0.2 on 2018-03-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0047_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='PlayerProfile',
        ),
    ]
