# Generated by Django 2.0.2 on 2018-07-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0048_auto_20180304_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='featured_month',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
