# Generated by Django 2.1.1 on 2019-01-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0049_adventure_featured_month_squashed_0051_adventure_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='special',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
