# Generated by Django 2.1.1 on 2019-02-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0051_hintanswer_spoiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='edx',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
