# Generated by Django 2.1.1 on 2019-02-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0052_auto_20190215_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='armor_class',
            field=models.IntegerField(default=0, help_text='(Armor only) How many hits does this armor protect against?', null=True),
        ),
    ]
