# Generated by Django 2.1.7 on 2019-04-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0053_auto_20190217_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='original_group_size',
        ),
        migrations.AddField(
            model_name='monster',
            name='name_plural',
            field=models.CharField(blank=True, help_text='The plural form of the name. Used only with group monsters.', max_length=255, null=True),
        ),
    ]
