# Generated by Django 2.2.1 on 2019-05-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0054_auto_20190412_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='intro_text',
            field=models.TextField(blank=True, default='', help_text='Text shown to the adventurer when they begin the adventure. Use this to set up the story. Split it into multiple pages by using a line containing three hyphens as a break. Supports Markdown.'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='description',
            field=models.TextField(help_text='Supports Markdown.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='effect',
            name='text',
            field=models.TextField(help_text='Supports Markdown.', max_length=65535),
        ),
        migrations.AlterField(
            model_name='hintanswer',
            name='answer',
            field=models.TextField(help_text='Supports Markdown.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='monster',
            name='description',
            field=models.TextField(help_text='Supports Markdown.', max_length=1000),
        ),
    ]
