# Generated by Django 2.2.1 on 2019-05-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0056_auto_20190526_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='is_markdown',
            field=models.BooleanField(choices=[(False, 'Plain text'), (True, 'Markdown')], default=0, verbose_name='Text format'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='is_markdown',
            field=models.BooleanField(choices=[(False, 'Plain text'), (True, 'Markdown')], default=0, verbose_name='Text format'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='is_markdown',
            field=models.BooleanField(choices=[(False, 'Plain text'), (True, 'Markdown')], default=0, verbose_name='Text format'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_markdown',
            field=models.BooleanField(choices=[(False, 'Plain text'), (True, 'Markdown')], default=0, verbose_name='Text format'),
        ),
    ]
