# Generated by Django 2.2.1 on 2019-07-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0057_auto_20190526_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='defense_bonus',
            field=models.IntegerField(default=0, help_text='Gives the monster an additional percent bonus to avoid being hit. (Rare)'),
        ),
    ]
