# Generated by Django 2.2.1 on 2019-07-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0058_auto_20190703_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='article',
            field=models.CharField(blank=True, help_text="Optional article or adjective that appears before the name, e.g., 'a', 'the', 'some'.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='article',
            field=models.CharField(blank=True, help_text="Optional article or adjective that appears before the name, e.g., 'a', 'the', 'some'. Does not apply to group monsters.", max_length=20, null=True),
        ),
    ]
