# Generated by Django 2.2.5 on 2019-10-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0059_auto_20190706_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomexit',
            name='message',
        ),
        migrations.AddField(
            model_name='room',
            name='dark_description',
            field=models.TextField(blank=True, help_text="The description shown if the room is dark and the player doesn't have a light. Leave blank to use the standard 'it's too dark to see' message.", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='dark_name',
            field=models.CharField(blank=True, help_text="The name shown if the room is dark and the player doesn't have a light. Leave blank to use the standard 'in the dark' message.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roomexit',
            name='effect_id',
            field=models.IntegerField(blank=True, help_text="The effect will be shown when the player moves in this direction. You can also enter a zero for the connection and an effect ID to set up a custom message on a non-existent exit, e.g., if the player can't go in the ocean without a boat, etc.", null=True),
        ),
    ]
