# Generated by Django 2.2.7 on 2019-12-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0060_auto_20191002_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='armor_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Armor'), (1, 'Shield'), (2, 'Helmet')], null=True),
        ),
        migrations.AlterField(
            model_name='playerartifact',
            name='armor_type',
            field=models.IntegerField(choices=[(0, 'Armor'), (1, 'Shield'), (2, 'Helmet')], default=0, null=True),
        ),
    ]
