# Generated by Django 3.0.5 on 2020-05-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0061_auto_20191213_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='armor_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Armor'), (1, 'Shield'), (2, 'Helmet'), (3, 'Gloves'), (4, 'Ring')], null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='style',
            field=models.CharField(blank=True, choices=[('', 'Normal'), ('emphasis', 'Bold'), ('success', 'Success (green)'), ('special', 'Special 1 (blue)'), ('special2', 'Special 1 (purple)'), ('warning', 'Warning (orange)'), ('danger', 'Danger (red)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='playerartifact',
            name='armor_type',
            field=models.IntegerField(choices=[(0, 'Armor'), (1, 'Shield'), (2, 'Helmet'), (3, 'Gloves'), (4, 'Ring')], default=0, null=True),
        ),
    ]
