# Generated by Django 3.0.5 on 2020-05-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0063_monster_combat_verbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('none', 'None')], max_length=6, null=True),
        ),
    ]
