# Generated by Django 3.0.5 on 2020-05-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0064_auto_20200529_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='data',
            field=models.TextField(blank=True, help_text='Adventure-specific data for this artifact, e.g., elemental weapon, etc.Enter as a JSON object.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='data',
            field=models.TextField(blank=True, help_text='Adventure-specific data for this monster, e.g., type of monster like vampire, undead, soldier, frost, etc. Data can be used in custom code. Enter as a JSON object.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='data',
            field=models.TextField(blank=True, help_text='Adventure-specific data for this room, e.g., room type or environment (road, cave, snow, etc.). Data can be used in custom code. Enter as a JSON object.', max_length=1000, null=True),
        ),
    ]
