# Generated by Django 3.0.5 on 2020-07-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0065_auto_20200529_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='guard_id',
            field=models.IntegerField(blank=True, help_text='If a bound monster, the ID of a monster that prevents the player from freeing it. For other artifact types, the ID of a monster that prevents the player from picking it up.', null=True),
        ),
    ]
