# Generated by Django 3.2.4 on 2021-07-28 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0066_auto_20200726_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='hintanswer',
            name='adventure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hint_answers', to='adventure.adventure'),
        ),
        migrations.AddField(
            model_name='roomexit',
            name='adventure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_exits', to='adventure.adventure'),
        ),
        # populate the fields added above
        migrations.RunSQL("update adventure_roomexit"
                          " set adventure_id ="
                          " (select adventure_id "
                          "  from adventure_room"
                          "  where adventure_room.id = adventure_roomexit.room_from_id)"),
        migrations.RunSQL("update adventure_hintanswer"
                          " set adventure_id ="
                          " (select adventure_id"
                          "  from adventure_hint"
                          "  where adventure_hint.id = adventure_hintanswer.hint_id)"),
    ]
